[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' cdnjs.cloudflare.com fonts.googleapis.com 'unsafe-inline' 'unsafe-eval';"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin"